[package]
name = "ctf-backend"
version = "0.1.0"
authors = []
edition = "2018"

[dependencies]
actix-cors = "0.3.0"
actix-files = "0.3.0"
actix-rt = "1.1.1"
actix-web = "3.0.2"
env_logger = "0.7.1"
http = "0.2.1"
lazy_static = "1.4.0"

[dev-dependencies]
actix-http = "2.0.0"
